### ISSUE TITLE
请问可以加上bypass插件吗？

### ISSUE THREAD

**Issue by smdx** [yaya131/X86_64-TEST#15]
感谢分享，非常好用。请问复刻后想加上bypass编译openwrt-immortalwrt要怎么做？谢谢

**Comment by smdx** [comment]
另外请教个问题想把解锁网易云编译进去是不是把config的
CONFIG_UnblockNeteaseMusic=y
CONFIG_UnblockNeteaseMusic_NodeJS=y
CONFIG_PACKAGE_luci-app-unblockneteasemusic=y
# CONFIG_PACKAGE_luci-app-unblockneteasemusic-go is not set
这样修改就可以了？谢谢

**Comment by jingleijack** [comment]
恩
