### ISSUE TITLE
项目推倒重来了吗？

### ISSUE THREAD

**Issue by smdx** [yaya131/X86_64-TEST#19]
作者好，这项目是推倒重来了吗？新的General.txt、X64.txt两个文档有很多重复项目的是？谢谢

**Comment by yaya131** [comment]
> 作者好，这项目是推倒重来了吗？新的General.txt、X64.txt两个文档有很多重复项目的是？谢谢

General.txt通用配置文件，X64.txt是X86基础文件！添加插件在通用配置文件里添加或删除即可
