### ISSUE TITLE
自动更新代码出错

### ISSUE THREAD

**Issue by souwei168** [yaya131/X86_64-TEST#4]
Run peter-evans/repository-dispatch@v1
  with:
    event-type: Source Code Update
    repository: souwei168/OPENWRT-LEAN
    client-payload: {}
  env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
Error: Parameter token or opts.auth is required

**Comment by jingleijack** [comment]
不清楚啊。你设置了啥
